### ISSUE TITLE
AWS EKS managed security group doubt

### ISSUE THREAD

**Issue by sabiram** [hashicorp/learn-terraform-provision-eks-cluster#101]
Hi

After applying the Terraform configuration, the cluster and corresponding node groups are created. However, I have a concern regarding the manual creation of an AWS EKS cluster from the console. In that process, the cluster security group is assigned to the node group, whereas here the node security group is attached to the node group. I'm uncertain if this behavior is expected. The necessary rules are attached to the security group, but I'm unsure if this assigning of security groups to worker nodes is a new feature. Please help

Thanks

**Comment by BrianMMcClain** [comment]
hi @sabiram! Sorry for taking so long to get to this issue. I'm going through now cleaning up this repo and did some looking around on this. I think the best source for further information is the [Network Connectivity](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/network_connectivity.md) documentation in the EKS module. This tutorial uses the default security group setting from the module, and the documentation goes through what those defaults are and why they were chosen. Hopefully this is helpful!
