### ISSUE TITLE
Organisation error when doing terraform init

### ISSUE THREAD

**Issue by andrewrotherham** [hashicorp/learn-terraform-provision-eks-cluster#109]
Hi, I'm on amazon linux 2, terrfaorm vesion 1.3.7 and I am getting an error wehen I do a terraform init, namely

```
│ Error: Invalid or missing required argument
│
│   on terraform.tf line 6, in terraform:
│    6:   cloud {
│
│ "organization" must be set in the cloud configuration or as an environment variable: TF_CLOUD_ORGANIZATION.
╵
```

any help gratefuly received

**Comment by BrianMMcClain** [comment]
Hi @andrewrotherham! Sorry for the delay getting back to you on this. By default, this example code assumes that you are using Terraform Cloud. If you are running the tutorial on Terraform Cloud, you can use the `TF_CLOUD_ORGANIZATION` environment variable to set the name of your TFC organization.

If you are running this tutorial locally just with the `terraform` CLI, you can remove or comment out the `cloud` block in the `terraform` block in the `terraform.tf` file:

```
terraform {
  /*
  cloud {
    workspaces {
      name = "learn-terraform-eks"
    }
  }
  */

  required_providers {
```

I'll go ahead and close this issue but if you run into any errors please feel free to reopen, and thank you for running our tutorials!
