### ISSUE TITLE
getting error after terraform apply

### ISSUE THREAD

**Issue by Deeresh** [hashicorp/learn-terraform-provision-eks-cluster#11]
module.eks.aws_autoscaling_group.workers[0]: Still creating... [2m20s elapsed]
module.eks.aws_autoscaling_group.workers[0]: Still creating... [2m30s elapsed]
module.eks.aws_autoscaling_group.workers[0]: Still creating... [2m40s elapsed]
module.eks.aws_autoscaling_group.workers[0]: Still creating... [2m50s elapsed]
module.eks.aws_autoscaling_group.workers[0]: Still creating... [3m0s elapsed]
module.eks.aws_autoscaling_group.workers[0]: Creation complete after 3m0s [id=training-eks-qyrm0cwY-worker-group-120200626153528568800000012]

Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp [::1]:80: connect: connection refused

  on .terraform/modules/eks/terraform-aws-eks-12.1.0/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
  64: resource "kubernetes_config_map" "aws_auth" {

**Comment by im2nguyen** [comment]
This has been addressed in #2  , thanks for flagging this
