### ISSUE TITLE
Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp 127.0.0.1:80: connect: connection refused

### ISSUE THREAD

**Issue by torlo** [hashicorp/learn-terraform-provision-eks-cluster#12]
Hello,

During terraform apply I face up with the issue:

module.eks.aws_autoscaling_group.workers[0]: Creation complete after 37s [id=training-eks-ibKAXDyK-worker-group-120200630082429115800000012]
module.eks.aws_autoscaling_group.workers[1]: Creation complete after 37s [id=training-eks-ibKAXDyK-worker-group-220200630082429109300000011]

**Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp 127.0.0.1:80: connect: connection refused

  on .terraform/modules/eks/aws_auth.tf line 64, in resource "kubernetes_config_map" "aws_auth":
  64: resource "kubernetes_config_map" "aws_auth" {**

Also, I found that Node groups weren't created.

**Comment by im2nguyen** [comment]
This has been addressed in #2  , thanks for flagging this. Please let me know if this is still an issue @torlo
