### ISSUE TITLE
Does this deprecate https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started?

### ISSUE THREAD

**Issue by emillg** [hashicorp/learn-terraform-provision-eks-cluster#16]
Hi,

I see https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started is different from this repo. Can someone explain why they are different? Which one should I use?

Thanks

**Comment by im2nguyen** [comment]
This repo uses the [EKS module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/12.2.0) to provision an EKS cluster. The repo you've provided contains the configuration to provision an EKS cluster using the actual resources.

You could use either. However, this repo provides a quick way to spin up an EKS cluster, instructions on how to connect to it and deploy resources to the cluster. The Learn guide associated with this repo can be found [here](https://learn.hashicorp.com/collections/terraform/kubernetes) and explains how this configuration in more details.

**Comment by emillg** [comment]
Thanks @im2nguyen
