### ISSUE TITLE
secrets is forbidden

### ISSUE THREAD

**Issue by mrkeyiano** [hashicorp/learn-terraform-provision-eks-cluster#18]
after following the whole process, and setting up the Kubernetes dashboard:
i got this in the notifications:

`secrets is forbidden: User "system:serviceaccount:kube-system:service-controller" cannot list resource "secrets" in API group "" in the namespace "default"`

**Comment by im2nguyen** [comment]
Hi @mrkeyiano , did you run the right command to [generate the authorization token](https://learn.hashicorp.com/tutorials/terraform/eks?in=terraform/kubernetes#authenticate-the-dashboard)? It seems like the token you generated is for the default` namespace instead of the `kube-system` namespace.

```
$ kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep service-controller-token | awk '{print $1}')

Name:         service-controller-token-46qlm
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: service-controller
              kubernetes.io/service-account.uid: dd1948f3-6234-11ea-bb3f-0a063115cf22

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1025 bytes
namespace:  11 bytes
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6I...
```
