### ISSUE TITLE
no k8s configmap

### ISSUE THREAD

**Issue by leartgjoni** [hashicorp/learn-terraform-provision-eks-cluster#2]
When removing `kubernetes.tf` (https://github.com/hashicorp/learn-terraform-provision-eks-cluster/commit/8410795aab0bf6fb2128d1a9bbf95138e4b5ca3e) no ConfigMap gets created, causing the worker nodes to be unable to join the eks cluster. This article: https://learn.hashicorp.com/terraform/kubernetes/provision-eks-cluster assumes that the nodes will join correctly.

**Comment by servomac** [comment]
I'm encountering an error reflected in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/699 when trying to use this example:

```
module.eks.null_resource.wait_for_cluster[0]: Creation complete after 2m11s [id=577447857153705578]
module.eks.kubernetes_config_map.aws_auth[0]: Creating...

Error: configmaps "aws-auth" already exists

  on .terraform/modules/eks/terraform-aws-eks-11.0.0/aws_auth.tf line 61, in resource "kubernetes_config_map" "aws_auth":
  61: resource "kubernetes_config_map" "aws_auth" {
```

I'm not sure if it is the same error that you are describing @leartgjoni.

**Comment by servomac** [comment]
I can config that adding the Kubernetes provider I have been able to create the cluter without that error:

```
provider "kubernetes" {	
  load_config_file       = "false"
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
}
```

**Comment by christianhxc** [comment]
thanks @servomac, I did the same and it works now :)

**Comment by gilescope** [comment]
@im2nguyen why remove kubernites.tf? It just seems to break everything - no reason was given in the commit message. Can we please unremove it so that this great tutorial works nicely out of the box?

**Comment by jervine-gogo** [comment]
This can also be resolved by uncommenting the output "config_map_aws_auth" section in the outputs.tf file. Not sure why this was commented as per the above, it disables the nodes to be able to join the k8s cluster.

**Comment by im2nguyen** [comment]
@gilescope yep, let me add that back in thanks for flagging it
