### ISSUE TITLE
Interpolation-only expressions are deprecated

### ISSUE THREAD

**Issue by atharvs** [hashicorp/learn-terraform-provision-eks-cluster#28]
While running the terraform scripts, I am getting below warnings at several places:
Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/vpc/outputs.tf line 353, in output "vpc_endpoint_sqs_id":
 353:   value       = "${element(concat(aws_vpc_endpoint.sqs.*.id, list("")), 0)}"

Versions:

terraform --version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

Let me know if any other inputs required

**Comment by alanszlosek** [comment]
This should now be fixed by #64 and #65. Please let us know if you are still having issues.
