### ISSUE TITLE
Including metadata for node groups

### ISSUE THREAD

**Issue by robincher** [hashicorp/learn-terraform-provision-eks-cluster#3]
Hi,

This is more of a question :).

Is there anyway i can labels the node groups? (In this case i am assuming the worker_groups in eks-cluster.tf).

Something like this ?
```
  worker_groups = [
    {
      name = "worker-group"
      metadata = [{
          role                 = "worker"
          os                   = "linux"
     ]}
      tags = [{
          key                 = "worker-group-tag"
          value               = "worker-group-1"
          propagate_at_launch = true
      }]
    }
  ]
```

**Comment by im2nguyen** [comment]
Hi @robincher, sorry about the late response.

 I don't believe `metadata` is a valid key for worker_groups, but your `tags` implementation should work. 

Valid keys for items in `work_groups` can be found here: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L36
