### ISSUE TITLE
Error updating cluster version from 1.19 to 1.20

### ISSUE THREAD

**Issue by sssanjaya** [hashicorp/learn-terraform-provision-eks-cluster#39]
https://github.com/hashicorp/learn-terraform-provision-eks-cluster/blob/d2e8d30f5bfe31f068322a544e07f3512c3b0e07/eks-cluster.tf#L4
```
module "eks" {
  source          = "terraform-aws-modules/eks/aws"
  cluster_name    = local.cluster_name
  cluster_version = "1.20" ### <<< changed from 1.19
  subnets         = module.vpc.private_subnets

```

**OUTPUT:**
`terraform plan`
```
module.eks.kubernetes_config_map.aws_auth[0]: Refreshing state... [id=kube-system/aws-auth]
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with module.eks.data.aws_ami.eks_worker_windows,
│   on .terraform/modules/eks/data.tf line 27, in data "aws_ami" "eks_worker_windows":
│   27: data "aws_ami" "eks_worker_windows" {
```

**Comment by im2nguyen** [comment]
Hi @sssanjaya, I just upgraded the provider versions and tested with `1.20`. I was able to provision the cluster successfully. 

Can you pull the latest configuration (this uses k8s v1.20) and try again? Thank you 😄

**Comment by sssanjaya** [comment]
wow, thank you so much. It was quick, gonna try it right away. Great job mate!
