### ISSUE TITLE
t4g.small not works on EKS

### ISSUE THREAD

**Issue by rafael-open** [hashicorp/learn-terraform-provision-eks-cluster#44]
### Problem
t4g.small instance type not works on EKS cluster  
  
### Output error
`Error: error creating EKS Node Group (my_eks_cluster:my_eks_node_group_t4gsmall_on_demand): InvalidParameterException: [t4g.small] is not a valid instance type for requested amiType AL2_x86_64`  
  
### How it was implemented
``` terraform
module "eks" {
  source             = "../../path_to_eks_module"
  cluster_name       = "eks_cluster"
  cluster_vpc_id     = data.aws_vpc.my_eks_vpc.id
  subnet_ids         = data.aws_subnet_ids.my_eks_subnet.ids
  private_subnet_ids = data.aws_subnet_ids.my_eks_private-subnet.ids
  cluster_role_name  = "my_eks_cluster_role"
  cluster_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "eks.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })
  cluster_policy_arn   = ["arn:aws:iam::aws:policy/AmazonEKSClusterPolicy", "arn:aws:iam::aws:policy/AmazonEKSServicePolicy"]
  cluster_sg_name      = "my_eks_cluster_sg"
  node_group_role_name = "my_eks_node_group_role"
  node_group_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "ec2.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })
  node_group_policy_arn = ["arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy", "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy", "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"]
  node_group_sg_name    = "my_eks_node_group_sg"
  node_group = {
    node_group_1 = {
      node_group_name = "my_eks_node_group_t4gsmall_on_demand"
      instance_types  = ["t4g.small"]
      ami_type        = "AL2_ARM_64"
      capacity_type   = "SPOT"
      desired_size    = 2
      min_size        = 1
      max_size        = 2
    }
  }
}
```

### Aditional info
Terraform provider version: 3.33.0 (also tried with 3.50.0)
OS: Linux Ubuntu 20.04 LTS

**Comment by im2nguyen** [comment]
Hello @rafael-open!

That's strange it should work -- https://serverfault.com/questions/1066931/why-cant-i-add-t4g-instances-to-my-eks-cluster. It's interesting that the node group AMI shows `AL2_ARM_64` in the configuration, but `AL2_x86_64` in the error. Can you try re-running a `terraform apply`?

If the problem isn't resolved, it might be faster to raise an issue in the [EKS module repo](https://github.com/terraform-aws-modules/terraform-aws-eks)

**Comment by rafael-open** [comment]
hi @im2nguyen 
I tried again, the problem persists.

**Comment by im2nguyen** [comment]
Can you raise an issue in the [EKS module repo](https://github.com/terraform-aws-modules/terraform-aws-eks)? Thanks!

**Comment by rafael-open** [comment]
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1494
