### ISSUE TITLE
server could not find the requested resource (post configmaps)

### ISSUE THREAD

**Issue by dbgurevich2017** [hashicorp/learn-terraform-provision-eks-cluster#5]
I'm trying to use this example. But when running terraform apply, I observe the following:

module.eks.null_resource.wait_for_cluster[0]: Creation complete after 2m11s [id=860621988250871190]
module.eks.kubernetes_config_map.aws_auth[0]: Creating...

Error: the server could not find the requested resource (post configmaps)

  on .terraform/modules/eks/terraform-aws-eks-11.1.0/aws_auth.tf line 62, in resource "kubernetes_config_map" "aws_auth":
  62: resource "kubernetes_config_map" "aws_auth" {

After this the process stops.

Is there a way to fix this?

The cluster is created and there are 3 EC2 instances running. I don't know if it is correct or not. Running "terraform output" looks OK.

**Comment by busbyjon** [comment]
I'm seeing this issue also.

I think EKS have updated some of their roles recently which could be impacting this.

**Comment by busbyjon** [comment]
OK - can confirm actions in #2 solved this for me.  The provider needs to be added and this error goes away

**Comment by im2nguyen** [comment]
This has been addressed in #2 , thanks for flagging this
