### ISSUE TITLE
terraform apply error

### ISSUE THREAD

**Issue by supun19** [hashicorp/learn-terraform-provision-eks-cluster#51]
`module.eks.aws_autoscaling_group.workers[0]: Creation complete after 1m18s [id=education-eks-Im6KCYIf-worker-group-120211102041313454300000015]
╷
│ Error: error reading Route Table (rtb-09cac278f6db9426e): couldn't find resource
│ 
│   with module.vpc.aws_route_table.public[0],
│   on .terraform/modules/vpc/main.tf line 198, in resource "aws_route_table" "public":
│  198: resource "aws_route_table" "public" {
│ 
╵`

**Comment by alanszlosek** [comment]
This should now be fixed by #65. Please let us know if you are still having issues.
