### ISSUE TITLE
Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.

### ISSUE THREAD

**Issue by MahmoudHaouachi2** [hashicorp/learn-terraform-provision-eks-cluster#59]
I'm getting this error when trying to create the stack

   with module.vpc.aws_eip.nat[0],
│   on .terraform/modules/vpc/main.tf line 1065, in resource "aws_eip" "nat":
│ 1065: resource "aws_eip" "nat" {

**Comment by alionur07** [comment]
Hi,
I fixed this issue by changing the region

**Comment by MahmoudHaouachi2** [comment]
hi,
I fixed it by increasing the service quota for Elastic IPs
