### ISSUE TITLE
What role/ policies are needed to run this terraform code?

### ISSUE THREAD

**Issue by tnguyen14** [hashicorp/learn-terraform-provision-eks-cluster#6]
What roles/ IAM policies should I assign to the programmatic user that will be running `terraform apply` on this example?

**Comment by tnguyen14** [comment]
I might be doing this wrong, but so far, I've attached these policies to the user:

- `AmazonEC2FullAccess` - AWS managed policy
- `IAMFullAccess`- AWS managed policy
- `AmazonVPCFullAccess` - AWS managed policy
- `EKSFullAccess` - custom policy - allow `eks:*` on all resources

**Comment by mijho** [comment]
The module you are using has the permissions listed, I don't think you'd need more than these.
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/iam-permissions.md

**Comment by tnguyen14** [comment]
I see. That's good to know. Could that link be referenced from this repo's doc?

**Comment by im2nguyen** [comment]
@tnguyen14 

Sorry about the late response -- thanks for flagging this! We merged your suggestion and it should be reflected in the guide now. 

![image](https://user-images.githubusercontent.com/7556325/88320130-ff333a80-ccd1-11ea-9348-4e6c94a71bcd.png)
