### ISSUE TITLE
'NoneType' object is not iterable while trying to update-kubeconfig

### ISSUE THREAD

**Issue by vvenkateshgupta** [hashicorp/learn-terraform-provision-eks-cluster#61]
aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

'NoneType' object is not iterable

**Comment by RamzesX** [comment]
I have to delte ~/.kube config file.
After deletion everything is ok.

**Comment by alanszlosek** [comment]
This should now be fixed by #65. Please let us know if you are still having issues.
