### ISSUE TITLE
Invalid principal in policy

### ISSUE THREAD

**Issue by lucas-huang-tfs** [hashicorp/learn-terraform-provision-eks-cluster#74]
While I run "terraform apply", the following error message is shown:

![image](https://user-images.githubusercontent.com/55420155/191686961-419b34b0-f745-483c-b2ce-881394259356.png)

Please note that I was trying to provision the EKS cluster in China region "cn-northwest-1".

**Comment by BrianMMcClain** [comment]
Hi @lucas-huang-tfs! Apologies for the delay responding to this. I've been doing some digging around this issue and do have one thing that might be useful.

I found [this issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1904) in the EKS module earlier in 2022 of someone facing a similar issue. From this issue, a new configuration parameter was introducedto customize the IAM role DNS suffix. Can you try adding the following to your Terraform config in the module declaration?

```
cluster_iam_role_dns_suffix = "amazonaws.com"
```

and let me know if you still have the issue? One other thing I'd like to note, we recently updated the tutorial and this repository to point to the latest version of the EKS module v19.0.4. It may be worth updating the configuration you're attempting to deploy to this latest version.

Hope this is helpful! 😄

**Comment by BrianMMcClain** [comment]
Closing for now, but if you're still experiencing this issue, please feel free to reopen! Thanks! 😄
