### ISSUE TITLE
`terraform init` broken

### ISSUE THREAD

**Issue by youtux** [hashicorp/learn-terraform-provision-eks-cluster#92]
Running `terraform init` on a fresh clone of this repo results in an error.

### Steps to reproduce
```shell
git clone https://github.com/hashicorp/learn-terraform-provision-eks-cluster
cd learn-terraform-provision-eks-cluster
terraform init
```

### Actual result
```
❯ terraform init
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/eks/aws 19.5.1 for eks...
- eks in .terraform/modules/eks
- eks.eks_managed_node_group in .terraform/modules/eks/modules/eks-managed-node-group
- eks.eks_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
- eks.fargate_profile in .terraform/modules/eks/modules/fargate-profile
Downloading registry.terraform.io/terraform-aws-modules/kms/aws 1.1.0 for eks.kms...
- eks.kms in .terraform/modules/eks.kms
- eks.self_managed_node_group in .terraform/modules/eks/modules/self-managed-node-group
- eks.self_managed_node_group.user_data in .terraform/modules/eks/modules/_user_data
Downloading registry.terraform.io/terraform-aws-modules/vpc/aws 3.19.0 for vpc...
- vpc in .terraform/modules/vpc

Initializing Terraform Cloud...
╷
│ Error: Invalid or missing required argument
│
│   on terraform.tf line 3, in terraform:
│    3:   cloud {
│
│ "organization" must be set in the cloud configuration or as an environment variable: TF_CLOUD_ORGANIZATION.
```

### Expected result
The command should succeed.

### Workaround
Adding `organization = "my-example-org"` to the `cloud` section (replace it with your own) seems to solve the issue:
```
terraform {

  cloud {
    organization = "my-example-org"
    workspaces {
      name = "learn-terraform-eks"
    }
  }

  required_providers {
...
```

### System info
OS: Mac os 13.2
Terraform: 1.3.7
Repo commit: 685bb971a4ed418d979e3bbab1eea9dfe05b0e6c

**Comment by BrianMMcClain** [comment]
Hi @youtux! Apologies for not updating you on this when we had updated the tutorial, we added a section of the tutorial to include instructions to set the `TF_CLOUD_ORGANIZATION` environment variable to fix this error and bring it in line with our other tutorials. I'll go ahead and marked this as closed, but if you're still experience any issues with the tutorial, please feel free to reopen. Thank you so much for pointing this out!
